### ISSUE TITLE
Search bar has disappeared

### ISSUE THREAD

**Issue by Anyerfillag** [thomaswang/minimal-twitter#40]
I noticed yesterday (23/10) that the search option and bar are missing when the extension is enabled; it doesn't show to the top right of the screen on the timeline or above the trending tags when on that page.

It will appear if I disable the extension, so I imagine some code needs tweaking slightly.

**Comment by Anyerfillag** [comment]
Whatever you did has fixed it - just noticed the bar is now back at the top the Explore/Trends page

**Comment by Sushubh** [comment]
just some offtopic thoughts... search works fine so that's great. but twitter broke focus on https://twitter.com/compose/tweet. i first thought it was happening due to minimal twitter but turns out it happens even when the addon is disabled. issues like these do not affect a lot of people so they rarely get fixed. thanks for the search fix though! god official twitter.com layout with trends in your face is so annoying! (i do wonder if there is a way for a browser add on to undo the retweet mess twitter caused this week!)

**Comment by thomaswang** [comment]
@Sushubh I would love to address UI issues like this! but doing free work for a multi-million $$$ corporation is not something anyone should do. They could, however, hire me to maintain this as an official add-on, but not sure how to even get their attention to ask for such a thing.
